AWSTemplateFormatVersion: 2010-09-09

Parameters:

  CloudWatchS3BucketName:
    Default: none
    Type: String

  EnableCloudWatchLogs:
    AllowedValues:
      - true
      - false
    Default: false
    Type: String

  KmsKeyArn:
    Default: none
    Type: String

  Sequence:
    Default: 1
    Type: Number

  Stage:
    Type: String

Conditions:

  EnableCloudWatchLogs: !Equals [ !Ref EnableCloudWatchLogs, true ]
  HasKmsKeyArn: !Not [ !Equals [ !Ref KmsKeyArn, none ] ]

Resources:

  IamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - ssm:UpdateInstanceInformation
              - ssmmessages:CreateControlChannel
              - ssmmessages:CreateDataChannel
              - ssmmessages:OpenControlChannel
              - ssmmessages:OpenDatachannel
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - s3:GetEncryptionConfiguration
            Effect: Allow
            Resource:
              - '*'
          - !If
            - HasKmsKeyArn
            - Action:
                - kms:Decrypt
                Effect: Allow
                Resource:
                  - !Ref KmsKeyArn
            - !Ref 'AWS::NoValue'
          - !If
            - EnableCloudWatchLogs
            - Action:
                - logs:CreateLogStream
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:PutLogEvents
              Effect: Allow
              Resource:
                - '*'
            - !Ref 'AWS::NoValue'
          - !If
            - EnableCloudWatchLogs
            - Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Effect: Allow
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${CloudWatchS3BucketName}
            - !Ref 'AWS::NoValue'
          - !If
            - EnableCloudWatchLogs
            - Action:
                - kms:GenerateDataKey
              Effect: Allow
              Resource:
                - '*'
            - !Ref 'AWS::NoValue'
      PolicyName: !Sub systems-manager-policy-${Stage}-${Sequence}

Outputs:

  PolicyId:
    Value: !Ref IamPolicy
